InviteMe/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InviteMe.Data;
using InviteMe.Models;
using InviteMe.Extensions;

namespace InviteMe.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
              return _context.EventCategories.Where(_ => _.TenantId == User.GetUserId()) != null ? 
                          View(await _context.EventCategories.Where(_ => _.TenantId == User.GetUserId()).ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.EventCategories'  is null.");
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.EventCategories.Where(_ => _.TenantId == User.GetUserId()) == null)
            {
                return NotFound();
            }

            var eventCategory = await _context.EventCategories.Where(_ => _.TenantId == User.GetUserId())
                .FirstOrDefaultAsync(m => m.Id == id);
            if (eventCategory == null)
            {
                return NotFound();
            }

            return View(eventCategory);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] EventCategory eventCategory)
        {
            eventCategory.Id = Guid.NewGuid();
            eventCategory.TenantId = User.GetUserId();
            _context.Add(eventCategory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));           
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.EventCategories == null)
            {
                return NotFound();
            }

            var eventCategory = await _context.EventCategories.FindAsync(id);
            if (eventCategory == null)
            {
                return NotFound();
            }
            return View(eventCategory);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,TenantId,Name,Description")] EventCategory eventCategory)
        {
            if (id != eventCategory.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eventCategory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventCategoryExists(eventCategory.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(eventCategory);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.EventCategories == null)
            {
                return NotFound();
            }

            var eventCategory = await _context.EventCategories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (eventCategory == null)
            {
                return NotFound();
            }

            return View(eventCategory);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.EventCategories == null)
            {
                return Problem("Entity set 'ApplicationDbContext.EventCategories'  is null.");
            }
            var eventCategory = await _context.EventCategories.FindAsync(id);
            if (eventCategory != null)
            {
                _context.EventCategories.Remove(eventCategory);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventCategoryExists(Guid id)
        {
          return (_context.EventCategories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

InviteMe/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InviteMe.Data;
using InviteMe.Models;
using InviteMe.Extensions;

namespace InviteMe.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContactsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contacts
        public async Task<IActionResult> Index()
        {
              return _context.Contacts.Where(_ => _.TenantId == User.GetUserId()) != null ? 
                          View(await _context.Contacts.Where(_ => _.TenantId == User.GetUserId()).ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Contacts'  is null.");
        }

        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Contacts.Where(_ => _.TenantId == User.GetUserId()) == null)
            {
                return NotFound();
            }

            var contact = await _context.Contacts.Where(_ => _.TenantId == User.GetUserId())
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // GET: Contacts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Email,PhoneNumber")] Contact contact)
        {
           
            contact.Id = Guid.NewGuid();
            contact.TenantId = User.GetUserId();
            _context.Add(contact);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));          
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Contacts == null)
            {
                return NotFound();
            }

            var contact = await _context.Contacts.FindAsync(id);
            if (contact == null)
            {
                return NotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,FirstName,LastName,Email,PhoneNumber,TenantId")] Contact contact)
        {
            if (id != contact.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contact);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactExists(contact.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Contacts == null)
            {
                return NotFound();
            }

            var contact = await _context.Contacts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Contacts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Contacts'  is null.");
            }
            var contact = await _context.Contacts.FindAsync(id);
            if (contact != null)
            {
                _context.Contacts.Remove(contact);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactExists(Guid id)
        {
          return (_context.Contacts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

InviteMe/Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InviteMe.Data;
using InviteMe.Models;
using InviteMe.Extensions;
using InviteMe.Models.ViewModels;
using FluentEmail.Core;
using InviteMe.MailService;

namespace InviteMe.Controllers
{
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly IEmailService _emailService;

        public EventsController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment, IEmailService emailService)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
            _emailService = emailService;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Events
                .Where(_ => _.TenantId == User.GetUserId())                
                .Include(_ => _.EventCategory);

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.Where(_ => _.TenantId == User.GetUserId())
                .Include(_ => _.EventCategory)
                .Include(_ => _.Invites)
                .ThenInclude(_ => _.Contact)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            ViewData["EventCategoryId"] = new SelectList(_context.EventCategories.Where(_ => _.TenantId == User.GetUserId()), "Id", "Name");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,EventImage,EventCategoryId,EventDateTime,AddressFirstLine,AddressSecondLine,AddressThirdLine,PostCode,MapUrl")] EventViewModel @event)
        {                                    
            var eventtime = DateTime.SpecifyKind(@event.EventDateTime, DateTimeKind.Utc);
            var dbEvent = new Event { 
                Id = Guid.NewGuid(), 
                TenantId = User.GetUserId(),
                Name = @event.Name,
                Description = @event.Description,
                EventDateTime = eventtime,
                EventCategoryId = @event.EventCategoryId,
                CreatedDate = DateTime.UtcNow,
                PostCode = @event.PostCode,
                MapUrl = @event.MapUrl,
                AddressFirstLine = @event.AddressFirstLine,
                AddressSecondLine = @event.AddressSecondLine,
                AddressThirdLine = @event.AddressThirdLine
            };            

            if (@event.EventImage != null)
            {
                dbEvent.ImageUrl = UploadedFile(@event);
            }
            _context.Add(dbEvent);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Checkin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkin(Guid Id)
        {

            var @invite = await _context.Invites.Include(_ => _.Contact).Include(_ => _.Event).SingleOrDefaultAsync(_ => _.Id == Id);
            if (@invite != null)
            {
                invite.Attended = true;
                invite.TimeCheckedIn = DateTime.UtcNow;                
                await _context.SaveChangesAsync();
            }                                              
            return Redirect(HttpContext.Request.Headers["Referer"]);
        }


        [HttpPost, ActionName("InviteContacts")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> InviteContacts(Guid EventId)
        {
            if (_context.Events == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Events'  is null.");
            }
            var @event = await _context.Events.FindAsync(EventId);
            if (@event != null)
            {
                var contacts = await _context.Contacts.Where(_ => _.TenantId == @event.TenantId).ToListAsync();

                if (contacts != null)
                {
                    foreach (var contact in contacts)
                    {
                        if (_context.Invites.Any(_ => _.EventId == @event.Id && _.ContactId == contact.Id))
                        {
                            continue;
                        }

                        _context.Invites.Add(new Invite
                        {
                            Id = Guid.NewGuid(),
                            ContactId = contact.Id,
                            EventId = @event.Id,
                            TenantId= @event.TenantId,
                            UniqueInviteKey = RandomString(6)
                        });
                    }
                }               
            }

            await _context.SaveChangesAsync();

            _context.Invites.Include(_ => _.Event).Include(_ => _.Contact).Where(_ => _.EventId == EventId).ForEach(_ => {
                _emailService.SendInvite(new EmailMetadata(_.Contact.Email, "You are Invited!"), $"InviteMe.Views.Shared.Invite.cshtml", _);
                });

            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(Guid id)
        {
          return (_context.Events?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private string UploadedFile(EventViewModel model)
        {
            string uniqueFileName = null;

            if (model.EventImage != null)
            {

                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.EventImage.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.EventImage.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        public static string RandomString(int length)
        {
            Random random = new Random();

            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
}

InviteMe/Views/Shared/EmailButtonView.cshtml
@using InviteMe.Views.Shared;

@model EmailButton;

<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td bgcolor="#ffffff" align="center" style="padding: 20px 30px 60px 30px;">
            <table border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td align="center" style="border-radius: 3px;" bgcolor="#539be2">
                        <a href="@Model.Url" target="_blank" style="font-size: 20px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; text-decoration: none; color: #ffffff; text-decoration: none; padding: 15px 25px; border-radius: 2px; border: 1px solid #539be2; display: inline-block;">
                            @Model.Text
                        </a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

InviteMe/Views/Shared/Invite.cshtml
@using InviteMe.Views.Shared;
@using InviteMe.Models;
@using InviteMe.Extensions;
@using QRCoder;
@using System.Drawing;
@model Invite;


@{
    Layout = "InviteMe.Views.Shared._EmailLayout.cshtml";
}

<p>
    Dear @(Model.Contact.FirstName + " " + Model.Contact.LastName), <br /> <br />
    We are excited to invite you to out event @(Model.Event.Name) with more details below
</p>

<br />

<p>
    Venue: @(Model.Event.AddressFirstLine+" "+Model.Event.AddressSecondLine) <br/>

    Date/Time: @(Model.Event.EventDateTime.ToString("dddd, dd MMMM yyyy  hh:mm tt"))

</p>

<br/>

<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td bgcolor="#ffffff" align="center" style="padding: 20px 30px 60px 30px;">
            <table border="0" cellspacing="0" cellpadding="0">                
                <tr>
                    <td align="center" style="border-radius: 3px;">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/d/d0/QR_code_for_mobile_English_Wikipedia.svg" width="400" height="400">
                    </td>
                <tr>
                    <td align="center" style="border-radius: 3px;" bgcolor="#539be2">
                        <a href="#" target="_blank" style="font-size: 20px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; text-decoration: none; color: #ffffff; text-decoration: none; padding: 15px 25px; border-radius: 2px; border: 1px solid #539be2; display: inline-block;">
                            @Model.UniqueInviteKey
                        </a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<br />

<p>
    If you have any questions, just reply to this email—we're always happy to help out.
</p>

InviteMe/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InviteMe</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InviteMe.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InviteMe</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - InviteMe - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InviteMe/Views/Shared/_SideNav.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> SignInManager

<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <div class="sb-sidenav-menu-heading">Reports</div>
@*            <a class="nav-link" asp-action="Index" asp-controller="Home" >
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Dashboard
            </a>*@

            <a class="nav-link" asp-action="Index" asp-controller="Events">
                <div class="sb-nav-link-icon"><i class="fas fa-champagne-glasses"></i></div>
                My Events
            </a>


            <a class="nav-link" asp-action="Index" asp-controller="Contacts" >
                <div class="sb-nav-link-icon"><i class="fas fa-address-book"></i></div>
                My Contacts
            </a>

            <a class="nav-link" asp-action="Index" asp-controller="Categories" >
                <div class="sb-nav-link-icon"><i class="fas fa-bars-staggered"></i></div>
                Manage Categories
            </a>


    @*        

            <div class="sb-sidenav-menu-heading">Activity</div>

            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                Invitations
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>*@
@*            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                    <a class="nav-link" href="layout-static.html">Static Navigation</a>
                    <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                </nav>
            </div>
            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                Pages
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                        Authentication
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="login.html">Login</a>
                            <a class="nav-link" href="register.html">Register</a>
                            <a class="nav-link" href="password.html">Forgot Password</a>
                        </nav>
                    </div>
                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                        Error
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="401.html">401 Page</a>
                            <a class="nav-link" href="404.html">404 Page</a>
                            <a class="nav-link" href="500.html">500 Page</a>
                        </nav>
                    </div>
                </nav>
            </div>
            <div class="sb-sidenav-menu-heading">Addons</div>
            <a class="nav-link" href="charts.html">
                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                Charts
            </a>
            <a class="nav-link" href="tables.html">
                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                Tables
            </a>*@
        </div>
    </div>
    <div class="sb-sidenav-footer">

        @if (SignInManager.IsSignedIn(User))
        {
            <div class="small">Logged in as:</div>
            <p>@User.Identity?.Name</p>
        }
    </div>
</nav>